### ISSUE TITLE
How can we Use it In android TV remote app ? How can we Integrate in Android project ?

### ISSUE THREAD

**Issue by mehrikhan007** [tronikos/androidtvremote2#14]
I have an Android TV remote control app currently working fine, I need to implement the feature of launching registered app in android TV or any other brand TV. Can I use this project for that purpose ? if yes, How ?

**Comment by tronikos** [comment]
Can you clarify what you are asking?

**Comment by mehrikhan007** [comment]
I'm sorry for confusion, 

I need to implement a feature in my current android app built on Kotlin, the feature I'm looking for is to launch the apps on the TV from my application, such as YouTube, Netflix, Amazon etc. 

I see that I can achieve it using your library, but since its developed using Python, I don't really know how I can use it with my android project. can you guide me through the process of integrating it in my android Project if it is possible ? 

Or is there any Kotlin or java based implementation available of this library ?

**Comment by tronikos** [comment]
Sorry I've no idea to both of your questions.

**Comment by mehrikhan007** [comment]
ohhh its okay, no problem
