### ISSUE TITLE
Implement using flask and uploading on live server

### ISSUE THREAD

**Issue by Jonny567** [tronikos/androidtvremote2#15]
Hi,

First of all thanks for such a great project. I am going to enhance it and make it more easier to use by using Flask with HTML and CSS. I made a flask app which include multiple android tv brands like SONY, OnePlus and Sansui etc. I need to know if I integrate your code with the remotes and upload it on live server will it work on live server ???

Thanks

**Comment by tronikos** [comment]
It will work only if the server is in the same local network.

**Comment by Jonny567** [comment]
Its good but I don't understand it correctly. Lets take an example suppose if I host this flask application on Hostinger or railway.app. And now I open that flask website URL in my browser using same wifi where my smart tv is also connected. Does it works.

**Comment by tronikos** [comment]
Isn't the Python code going to run on the server?

**Comment by Jonny567** [comment]
no there should be integrated your android code and if I host it somewhere on live server will it works there. Will it works if I host this project on server and open this website in my android device and my browser and smart tv also connected to same network will it works in this case

**Comment by Jonny567** [comment]
also take a look here https://flask-gouc-production.up.railway.app. Kindly open this url in mobile device for better view

**Comment by tronikos** [comment]
I have a hard time understanding what you are asking but I don't think it's possible.
