### ISSUE TITLE
How to launch any app such as Kodi

### ISSUE THREAD

**Issue by albaintor** [tronikos/androidtvremote2#17]
Hi,

Actually this is not possible to launch any app if no url scheme is defined, and this is not possible to retrieve the list of installed apps.

The Nvidia shield tv app can retrieve the app list and launch any app as in the capture below.
Is it using the same remote service as you do ? 
![image](https://github.com/tronikos/androidtvremote2/assets/118518828/f691f2cb-bcf3-4156-90cd-f958c09068d4)

Also I saw on another python implementation (but I couldn't run it due to old dependencies) : https://github.com/farshid616/Android-TV-Remote-Controller-Python
There is a "send_lunch_app_command" method that could launch any application with an example : "intent:#Intent;component=com.netflix.ninja/.MainActivity;end". I couldn't reproduce it on your integration

Thank you for your help, I can help for the implementation

Here is another screenshot (with kodi) :
![Capture décran  2024-03-14 à 10 09 07 (002)](https://github.com/tronikos/androidtvremote2/assets/118518828/5f0a171c-c432-40f6-bba9-5dcefa1fe616)

**Comment by tronikos** [comment]
That's right. You can only send URLs which means you can't run apps such as KODI that don't have one registered. But you should be able to use the Android ADB integration for such apps.

I believe the NVIDIA SHIELD TV is using a very similar protocol but extended for additional functionality. If you want to reverse engineer that and implement it, take a look at:

- https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/shieldtv
- https://community.openhab.org/t/nvidia-shield-binding-successfully-decoded-protocol-looking-for-binding-coding-help/141610
- https://community.openhab.org/t/androidtv-binding-3-2-0-4-2-0/142203

**Comment by tronikos** [comment]
I forgot to mention that https://github.com/farshid616/Android-TV-Remote-Controller-Python is for the old V1 protocol. It's also linked in this repo under credits.

**Comment by albaintor** [comment]
Thank you for your feedback. I would like to avoid adb as this is intended to be used by the Unfolded Circle remote control which holds an android tv integration based on your library so ADB is not possible and requires additional administration. Adb is slow by the way

**Comment by tronikos** [comment]
I don't use adb either because it's slow. That's the reason I created this library and the Home Assistant integration.
Did you open a feature request to Kodi? They just need to add the following lines in their manifest:

```xml
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <data android:scheme="kodi"/>
            </intent-filter>
```

and then we will be able to open it with `kodi://`

Note the above was based on what Plex is using, see https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921

It will be faster to just send them a PR with these changes.

**Comment by tronikos** [comment]
From https://github.com/tronikos/androidtvremote2/issues/20

> I submitted a PR to Kodi's team to have deeplinks, meanwhile we found a workaround with this URL "market://launch?id=org.xbmc.kodi"

Good to hear! Can you link to the PR? I assume the workaround opens Play Store and you have to select open to launch the app? Could you edit https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921 and maybe even https://www.home-assistant.io/integrations/androidtv_remote/ with this workaround? This seems very useful especially since it can work on any installed app.

**Comment by albaintor** [comment]
The workaround opens Kodi directly without going through the store. 

Finally the PR is on the form they don't accept feature request through GitHub. https://forum.kodi.tv/showthread.php?tid=377296

**Comment by Drafteed** [comment]
> I submitted a PR to Kodi's team to have deeplinks, meanwhile we found a workaround with this URL "market://launch?id=org.xbmc.kodi"

Wow, great way to run any application by `app_id`! 
I tried it on my devices - it allows you to run any application, not even from the Google Play Store, **without any confirmation**.

```
TiviMate:
market://launch?id=ar.tvplayer.tv

SmartTube (not from Play Store):
market://launch?id=com.teamsmart.videomanager.tv

Twitch:
market://launch?id=tv.twitch.android.app

Steam Link:
market://launch?id=com.valvesoftware.steamlink
```

@tronikos Maybe we should add a handler to the `media_player.play_media` service in HA integration?
```
service: media_player.play_media
data:
  media_content_type: app
  media_content_id: com.teamsmart.videomanager.tv
target:
  entity_id: media_player.living_room_tv
```

**Comment by tronikos** [comment]
Thanks for confirming this trick actually works on all apps. I want to change this library to add market://launch?id= if the link doesn't have scheme and update all documentation. I'll try to do that tonight.

**Comment by Drafteed** [comment]
> I want to change this library to add market://launch?id= if the link doesn't have scheme and update all documentation. I'll try to do that tonight.

I would rather suggest implementing this as a separate service. It seems to me that trying to detect the presence of a scheme ( `://` substring i think) is not a very elegant solution. Could there be schemes that we don't know about that don't contain `://`?

My suggestion: https://github.com/home-assistant/core/compare/dev...Drafteed:home-assistant:atvremore-play-media-app?expand=1

**Comment by Drafteed** [comment]
Doc PR: https://github.com/home-assistant/home-assistant.io/compare/next...Drafteed:home-assistant.io:atvremote-media-play-app?expand=1

**Comment by Drafteed** [comment]
Core PR: https://github.com/home-assistant/core/pull/116896

**Comment by tronikos** [comment]
> It seems to me that trying to detect the presence of a scheme ( `://` substring i think) is not a very elegant solution. Could there be schemes that we don't know about that don't contain `://`?

Scheme is required for deep links so deep links will always have `://`. In addition, package names can't have `://` in them.

**Comment by Drafteed** [comment]
> Scheme is required for deep links so deep links will always have ://

`uri:content` is also valid URI, eg. `mailto:example@example.com`, `tel:+123455678`, `geo:55.79378663446035,49.11699501723111`, `sms:+18432776410?body=hello%20test`,  does not contain `://`, but can handled by the Android TV service and your lib before `1.x.x`.

`//example.com` is also valid domain (https://www.paulirish.com/2010/the-protocol-relative-url/).
`magnet:?xt=urn:btih:19ab7ff03d14dda05a15445374ad68bf55ada321&dn=Name` is valid magnet link. 
`[isbn:0393315703]` is also valid URI (https://en.wikipedia.org/wiki/CURIE).

https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

![image](https://github.com/tronikos/androidtvremote2/assets/11841379/7d06929b-6b34-49c7-bad8-279f35c9af7e)

**Comment by tronikos** [comment]
Thanks. https://github.com/tronikos/androidtvremote2/commit/c5d7292e8efe6201854884d8402572398ee11c2a should take care of most of these edge cases.

**Comment by Dillton** [comment]
Hello @tronikos,

finally opening Kodi is working thank you very much however I found one app used in Czechia as IPTV service which won't open with market://launch?id=cz.sledovanitv.android or just cz.sledovanitv.android.
App name is SledovaniTV.

What happens is only the store page of the app is opened.
Do you or anyone have any idea why?

**Comment by tronikos** [comment]
No sorry
