### ISSUE TITLE
Connection not closed under Linux when the Android TV device is physically disconnected (unplugged or network disconnected)

### ISSUE THREAD

**Issue by tronikos** [tronikos/androidtvremote2#2]
Reported by @Drafteed in https://github.com/home-assistant/core/pull/89935

"I have found that when the Android TV device is physically turned off, the entity in the HA remains on. Moreover, it looks like the connection is not being closed/recreated, and if the device comes back online, the next command will be ignored (as the reconnect process starts)."

I was able to reproduce this only under Linux. Under Windows the connection is correctly closed after about 10 seconds.
Either try to understand the differences between the OS implementations and fix it under Linux or close the connection if there is no "ping"  from the Android TV device. The server (Android TV device) keeps sending ping requests every 5 seconds and if the client doesn't respond back within some X seconds the connection is closed by the server. Similarly we could close the connection from the client if the server doesn't send the ping for X seconds.

**Comment by Drafteed** [comment]
Unfortunately, it did not help when disconnecting, but it looks like now the connection is re-created when the device is back online.

https://user-images.githubusercontent.com/11841379/230354062-7b2a45c4-b8e6-4bfc-bcbd-dcce4c9c90df.mp4

**Comment by tronikos** [comment]
Did you restart Home Assistant after bumping the version?

**Comment by tronikos** [comment]
I can reproduce it on my Philips TV but not on the Nvidia Shield. Reopening.

**Comment by tronikos** [comment]
I think this time I really fixed it. Can you please confirm changes in https://github.com/home-assistant/core/pull/91001 are fixing this?

**Comment by Drafteed** [comment]
Yes, now the status is displayed correctly 👍.

**Comment by Drafteed** [comment]
If you mind, I'll ask here. 

[Here I suggested](https://github.com/home-assistant/core/pull/89935#issuecomment-1475422884) adding a `media_player` platform. Are you planning to do this? I can try to do it myself.

**Comment by tronikos** [comment]
Thanks for confirming!

No I'm not planning to. As I said the cast integration works well enough for me. I don't quite like the idea supporting media player because the protocol used isn't meant for that, e.g. no playback status and no (or limited) play media support.
