### ISSUE TITLE
Exception not caught when network connection is lost

### ISSUE THREAD

**Issue by albaintor** [tronikos/androidtvremote2#20]
Hi,

when the connection is closed (androidtv is in standby or powered off), the exception is caught by your library and would reconnect after when restablished.
However when a network exception on client side occurs (wifi connection lost on client side for example), the exception is not caught.
I have submitted a PR to fix this problem

Otherwise, it has nothing to do : I submitted a PR to Kodi's team to have deeplinks, meanwhile we found a workaround with this URL "market://launch?id=org.xbmc.kodi"

Thank you

**Comment by tronikos** [comment]
Fixed in v0.0.15
